# https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf

##################
# video settings #
##################

# Do not close the window on exit.
#keep-open=yes

##################
# other settings #
##################


# https://wiki.archlinux.org/index.php/Mpv#High_quality_configurations
# Use 5MB input cache by default. The cache is enabled for network streams only.
cache-default=5000

# Use 150MB input cache for everything, even local files.
cache=300600
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

video-sync=display-resample
interpolation
tscale=oversample
load-unsafe-playlists
